In [1]:
    # install python package - numpy 
    # pip install numpy

In [2]:
import numpy as np

In [3]:
myList=[1,2,3,4,5]

In [4]:
print(myList)

[1, 2, 3, 4, 5]


In [5]:
type(myList)

list

In [6]:
#dir(np)

In [7]:
#help(np)

In [8]:
arr = np.array(myList)

In [9]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
# shape of the array
arr.shape

(5,)

In [11]:
arr.size

5

In [12]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr = np.array([my_list1,my_list2,my_list3])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.shape

(3, 5)

In [16]:
arr.size

15

In [17]:
# numpy array indexing

my_list1=[1,2,3,4,5]
arr = np.array(my_list1)

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
print(arr[0])

1


In [20]:
# get the second element from following array
print(arr[1])

2


In [21]:
# get third and fourth element from following array add them
print("the third element is",arr[2],"and the fourth element is",arr[3])

the third element is 3 and the fourth element is 4


In [22]:
# access 2D array

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr = np.array([my_list1,my_list2,my_list3])

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
print("2nd element on 1st row:",arr [0,1])

2nd element on 1st row: 2


In [25]:
# getting element on 2nd row,5th column
arr[1,4]

6

In [26]:
valarr = np.array([[1,2,3],[4,5,6]])

In [27]:
print("printing the variable value:",valarr)


printing the variable value: [[1 2 3]
 [4 5 6]]


In [28]:
print("printing the shape:",valarr.shape)

printing the shape: (2, 3)


In [29]:
print("printing the size:",valarr.size)

printing the size: 6


In [30]:
print("first row first element:",valarr[0,0])

first row first element: 1


In [31]:
print("printing second row third element:",valarr[1,2])

printing second row third element: 6


In [32]:
newarr=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])

In [33]:
print("printing the variable value",newarr)

printing the variable value [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]


In [34]:
print("printing the shaoe",newarr.shape)

printing the shaoe (5, 5)


In [35]:
print("printing the size",newarr.size)

printing the size 25


In [36]:
print("second row third element",newarr[1,2])

second row third element 8


In [37]:
# negative indexing

mylist=[1,2,3,4,5,6,7]
arr=np.array(mylist)

#print (arr)

valarr=np.array([[1,2,3],[4,5,6]])

In [38]:
print(valarr)

[[1 2 3]
 [4 5 6]]


In [39]:
valarr[0,-1]

3

In [40]:
valarr[1,-2]

5

In [41]:
# numpy array slicing -1D

mylist=[1,2,3,4,5,6,7,8,9,10]

arr=np.array(mylist)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [42]:
# arr[start:end]

arr[0:5]

array([1, 2, 3, 4, 5])

In [43]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [44]:
arr[:5]

array([1, 2, 3, 4, 5])

In [45]:
arr[:-1]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[-3:-1]

array([8, 9])

In [47]:
arr[: :2]

array([1, 3, 5, 7, 9])

In [48]:
arr[1: :2]

array([ 2,  4,  6,  8, 10])

In [49]:
arr[1: :3]

array([2, 5, 8])

In [50]:
# slicing 2D arrays

my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]

arr = np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [51]:
arr[1 :,:]

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [52]:
arr[1:,1:]

array([[3, 4, 5, 6],
       [7, 6, 8, 9]])

In [53]:
arr[: ,1:]

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [7, 6, 8, 9]])

In [54]:
arr[1:,1:4]

array([[3, 4, 5],
       [7, 6, 8]])

In [55]:
arr[:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [56]:
# Arange function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [59]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [60]:
# Linspace

np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [61]:
arr = np.array([1,2,3,4])  # let numpy choose the datatype
print(arr.dtype)

int64


In [62]:
arr = np.array([1.0,2.0])
print(arr.dtype)

float64


In [63]:
arr = np.array(['apple','banana','cherry'])
print(arr.dtype)

<U6


In [64]:
arr = np.array(['apple','banana','cherry','bananacherry'])
print(arr.dtype)

<U12


In [65]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [66]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [67]:
arr = np.array([1,2,3,4,5],dtype=np.float32)
print(arr.dtype)

float32


In [68]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [69]:
# array math
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [70]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [71]:
x+y

array([[ 6,  8],
       [10, 12]])

In [72]:
x-y

array([[-4, -4],
       [-4, -4]])

In [73]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [74]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [75]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [76]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [77]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [78]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8],[9,10]],dtype=np.float64)

In [79]:
x.shape

(2, 2)

In [80]:
y.shape

(3, 2)

In [81]:
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [ ]:
np.subtract(x,y)

In [ ]:
np.divide(x,y)

In [ ]:
np.multiply(x,y)

In [ ]:
np.exp(x)

In [ ]:
np.log(x)

In [ ]:
np.cos(x)

In [ ]:
np.tan(x)

In [ ]:
# floor, ceil, round
x = np.array([[1.5,2.6],[3.1,4.9]],dtype=np.float64)

In [ ]:
x

In [ ]:
np.floor(x)

In [ ]:
np.ceil(x)

In [ ]:
np.round(x)dr

In [ ]:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
z = np.array([[9,10],[11,12]],dtype=np.float64)

In [ ]:
x*y*z

In [ ]:
np.multiply(x,y,z)

In [ ]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

In [ ]:
v.dot(w)

In [ ]:
np.dot(v,w)

In [ ]:
x

In [ ]:
x.shape

In [ ]:
np.sum(x)

In [ ]:
# sum calculated row wise
np.sum(x,axis=1)

In [ ]:
#axis=0/1 0:column , 1:row

In [ ]:
np.sum(x,axis=0)

In [ ]:
# Transpose, T
x.T

In [ ]:
# numpy array copy vs view
arr = np.array([1,2,3,4,5])
x = arr

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
arr[0]

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
x[1]=200

In [ ]:
print(x)

In [ ]:
print(arr)

In [ ]:
# numpy array copy 
arr = np.array([1,2,3,4,5])
x = arr.copy()

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
arr[0]=100

In [ ]:
print(arr)

In [ ]:
print(x)

In [ ]:
x[1]=200

In [ ]:
print(x)

In [ ]:
print(arr)

In [ ]:
# numpy array reshaping
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
np.arange(1,13)
arr.shape

In [ ]:
arr.reshape(3,4)

In [ ]:
arr_new=arr.reshape(4,3)

In [ ]:
arr_new  # 1D-----> 2D

In [ ]:
# flattening the arrays
# 2D----->1D
arr_new.reshape(-1)

In [ ]:
# iterating arrays
arr=np.arange(1,7).reshape(3,2)

In [ ]:
arr

In [ ]:
for x in arr:
    print(x)

In [82]:
# joining numpy arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [83]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [84]:
# join 2-D arrays along rows(axis=1)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [85]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [86]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])